name: 'Weekly sync from upstream repository'

on:
  schedule:
    - cron: '0 6 * * 2,4'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync HEAD with Upstream
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Sync com Upstream
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: "n8n-io/n8n"
          upstream_sync_branch: "master"
          target_sync_branch: "main"
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."

      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}
